#!/bin/bash
clear
echo "-------------"
echo "bash -n wiz"
bash -n wiz
echo " "
echo "-------------"
echo "bash -n wizard.sh"
bash -n wizard.sh
echo " "
echo "-------------"
echo "bash -n common-wiz.sh"
bash -n common-wiz.sh
echo " "
echo "-------------"
echo "bash -n package-wiz.sh"
bash -n package-wiz.sh
echo " "
echo "-------------"
echo "bash -n arch-wiz.sh"
bash -n arch-wiz.sh
echo " "
echo "-------------"
echo "bash -n packages.sh"
bash -n packages.sh
echo " "
echo "-------------"

